files: /*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        files: src
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.3
    hooks:
    -   id: ruff
